apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-journal-view
  labels:
    plugin.halo.run/role-template: "true"
  annotations:
    plugin.halo.run/module: "Journal Management"
    plugin.halo.run/display-name: "日志查看"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:journals:view"]
rules:
  - pluginName: PluginJournals
    resources: [ "journals" ]
    verbs: [ "get", "list" ]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-journal-manage
  labels:
    plugin.halo.run/role-template: "true"
  annotations:
    plugin.halo.run/module: "Journal Management"
    plugin.halo.run/display-name: "日志管理"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:journals:manage"]
    rbac.authorization.halo.run/dependencies: |
      ["role-template-journal-view"]
rules:
  - pluginName: PluginJournals
    resources: [ "journals" ]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]
